[build]
  publish = "dist"
  command = "npm run build"

# Handle SPA routing - redirect all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to your backend during development
[[redirects]]
  from = "/api/*"
  to = "https://digital-land-survey-backend.onrender.com/api/:splat"
  status = 200
  force = true
  conditions = {Role = ["admin", "owner"]}

[context.production.environment]
  VITE_API_URL = "https://digital-land-survey-backend.onrender.com/api" 